AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  waf-ip-whitelist-manager

  Sample SAM Template for waf-ip-whitelist-manager

Globals:
  Function:
    Timeout: 30

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - AWSWAFFullAccess
        - AWSLambdaExecute
      Events:
        LambdaFunctionApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  LambdaFunctionApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  LambdaFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt LambdaFunction.Arn
  LambdaFunctionIamRole:
    Description: "IAM Role"
    Value: !GetAtt LambdaFunctionRole.Arn
